### ISSUE TITLE
Gamemode 1 glitch

### ISSUE THREAD

**Issue by optifinecape** [FrozenOrb/TeamPractice#11]
People glitch into creative gamemode through parties and 1v1s(/spectate possibly) (players can throw pots, spawn in any items, throw any items, etc.)

**Comment by optifinecape** [comment]
Figured out case of it!
1) Start a duel with 3 or more people
2) One person dies, and when in spectate mode does /bukkit:kill
3) They get tped to spawn, and have gamemode and /spectate vanish until everyone in the team is dead

You can also do /bukkit:tell to message people in a wierd way. (Possibly other /bukkit's work, i haven't tested all of them).

**Comment by ToniTang** [comment]
Should be fixed thanks to permission fixes by @jhalt.
