### ISSUE TITLE
Glitching up the spawn red glass wall

### ISSUE THREAD

**Issue by epicvisions101** [FrozenOrb/TeamPractice#21]
After leaving spawn players are able glitch climb up the red glass wall pretty high. This spams alerts saying they're flying. 

Seen this a few times now, luckily few people know about it yet.

**Comment by macguy8** [comment]
We can't v do much about this -- it's just how the game behaves when dealing with 'phantom' blocks. So long as our staff know not to ban off of alerts I don't see it being a problem.

**Comment by ToniTang** [comment]
^
