### ISSUE TITLE
Kit chests at spawn need to be cleaned up, add milk, gold armor, remove random speed)

### ISSUE THREAD

**Issue by ToniTang** [FrozenOrb/TeamPractice#5]

**Comment by optifinecape** [comment]
Remove speed potion next to the slowness
Make it so the armour chest has ALL the items in the /kits, (with the exception of bard items).
Add: Gold armour, milk
If short on space, make another chest and extend boards (make it kinda like cubecore kohi)

The pot chest closest to the spawning point is missing 4 insta 2 potions? add them back

**Comment by macguy8** [comment]
@optifinecape You can do this yourself, right click on the chest with a book and quill to actually edit it (as opposed to the 'normal' view)

**Comment by optifinecape** [comment]
@ToniTang @macguy8  how do i make a double Armour chest without making it a normal chest?
